name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      restore-keys: |
        ${{ runner.os }}-nuget-
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal  --logger "trx" --results-directory "./TestResults"

    - uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Test Results
        path: TestResults/*.trx
        reporter: dotnet-trx

  publish:
    runs-on: ${{matrix.os}}
    name: publish-${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    needs: build
    if: ${{ github.event_name != 'pull_request' }} # don't upload artifacts for PRs
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      with:
      path: ~/.nuget/packages
      key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
      restore-keys: |
        ${{ runner.os }}-nuget-
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish MVC
      run: dotnet publish PlayGames/PlayGames.csproj -c Release
    - name: Upload MVC artifact
      uses: actions/upload-artifact@v3
      with:
        name: ConsoleGames-${{matrix.os}}
        path: PlayGames/bin/Release/net6.0/publish/
